stages:
  - build
  - test

build:
  image: node:12.4.0-alpine
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build:ci
  artifacts:
    paths:
      - dist

build-docs:
  image: node:12.4.0-alpine
  stage: build
  before_script:
    - npm ci
    - apk add curl
    - apk add jq
  script:
    - npm run build:docs:ci
    - PR_ID=$(curl -s -L "http://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/merge_requests?private_token=${OAUTH_TOKEN}&state=opened" | jq -r ".[]|select(.sha == \"$CI_COMMIT_SHA\")|.iid")
    - node ./pipeline/post-comment.js
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - documentation

test:
  image: circleci/node:12.4.0-browsers
  stage: test
  before_script:
    - npm ci
  script:
    - npm run test:ci
  artifacts:
    paths:
      - coverage
    reports:
      junit: JUnit/report.xml
  coverage: '/(\d*.?\d+)%/'
  needs:
    - build
  dependencies:
    - build

